[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lspinstall"
version = "0.4.0"
dependencies = [ "requests" ]

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "black", "isort"]

[project.scripts]
lspinstall = "lspinstall.main:main"
